#!/bin/bash
#
#Userdata on XEN VM  to perform a full automated provisioning of VM on XEN hypervisors
##

test -n "$1" && source $1

function main() {
	#Main function to run all the module automation

	#Loading basic library
	test -f "./lib/basic.sh" && \
	source "./lib/basic.sh" || \
	exit "${LINENO}"

	initialize_vars
	check_state
	check_exit \
		"$?" \
		"Check&Get parameter 'state'." \
		"Check&Get parameter 'state' ${state}" \
		"fail" \
		"${LINENO}"

	#Include the selected operation.
	#If not exist ERROR
	test -f "./cmd/${state}.sh" && \
	source "./cmd/${state}.sh" || \
	exit "${LINENO}"
	
	${state}
}

main