- hosts: target
  connection: ssh
  become: true
  tasks:
    - name: Create VM
      easyxen:
        state: present
        vm_name: "{{ vm_name }}" 			#easyxen_vm
        cpu: "{{ cpu }}" 					#2
        ram: "{{ ram }}" 					#2048
        netmask: "{{ netmask }}" 			#255.255.255.0
        gateway: "{{ gateway }}" 			#192.168.1.1
        ip_address: "{{ ip }}" 				#192.168.1.12
        mac_address: "{{ mac_address}}" 	#02:00:00:45:9a:2c
        distro: "{{ distro }" 				#centos/debian/redhat/ubuntu
        os_user: "{{ vm_user }}" 			#ec2-user, xen-user, mary, rosy ecc...
        pub_key: "{{pub_key}}"				#raw-key like => ssh-rsa AA..root@github.com
        image: "{{ image }}"				#image to run centos7.xva, centos6.xva, debian7.xva
        disk_to_mount: 0 					#Disk position to mount for the network configuration